### ISSUE TITLE
Create UI for compose broadcast message

### ISSUE THREAD

**Issue by kadetXx** [hngi/sentry-my-customer-frontend#125]
This UI will have the following
- [ ] Message title
- [ ] Message body
- [ ] Select recipents
- [ ] the UI should be similar in design to the users list UI 
- [ ] the UI should have elements from the mobile design

**Comment by Razeb12** [comment]
I am working on this task assigned to me my Kadet
Slack ID: @Razeb

**Comment by kadetXx** [comment]
Approved

**Comment by Razeb12** [comment]
@kadetXx done and PR made
