### ISSUE TITLE
Fix mobile menu - FE

### ISSUE THREAD

**Issue by kadetXx** [hngi/sentry-my-customer-frontend#128]
[ ] Change colours and styling of mobile menu to suit UI design

**Comment by hadeelsala7** [comment]
I am working on this task, assigned to me by Kadet
My slack ID is @HNG-03648

**Comment by hadeelsala7** [comment]
I am working on this task, assigned to me by Kadet
My slack ID is **'@Hadeel'**

**Comment by kadetXx** [comment]
Approved
