### ISSUE TITLE
Sign up page not displaying error messages from API

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#135]
If you open the signup form and fill incorrect info, for example, the wrong email, it will show you a 500 error page.
this is because the person who worked on it returned the 500 page if there is an error.

Code snippet
` catch (\Exception $e) {
            Log::error('Catch error: RegisterController - ' . $e->getMessage());
            return view('errors.500');
        }`

You are required to refactor his codes, such that when there is an error, it should be displayed on to the user
Files to change :
- RegisterController
- Signup view file.

Comment below if you do not understand or have a question

**Comment by devYusuf** [comment]
Okay, I will jump into it.
