### ISSUE TITLE
Take me Home 

### ISSUE THREAD

**Issue by Ezeko** [hngi/sentry-my-customer-frontend#235]
Make take me home return to dashboard if logged in and return to home if not logged in

**Comment by Ezeko** [comment]
#236

**Comment by Ezeko** [comment]
#268

**Comment by sosualfred** [comment]
Is the issue still not fixed?

**Comment by sosualfred** [comment]
If it is not give a brief overview of the problem so I can work on it.

**Comment by Ezeko** [comment]
It had been fixed. Long ago
