### ISSUE TITLE
Implement Complaints Form

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#24]
You are required to:
- [ ] Post the data collected from the complaints form to the database

**Comment by Totoola-Kehinde** [comment]
I will be taking this up! API integration to post complaints from the forms to the DB

**Comment by kofimokome** [comment]
please  wait
till you are assinged
@Totoola-Kehinde

**Comment by kofimokome** [comment]
assigned to naijabas

he was already working on it before the issue moved to gitub

**Comment by patrickcyubahiro** [comment]
I am working on this issue.

**Comment by kofimokome** [comment]
approved
