### ISSUE TITLE
Implement User List

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#31]

**Comment by devYusuf** [comment]
I did this https://github.com/hngi/sentry-my-customer-frontend/pull/46

**Comment by kofimokome** [comment]
you closed the PR, so that means the work has not yet been submitted

**Comment by kofimokome** [comment]
what is your slack username?

**Comment by kofimokome** [comment]
@Tokyo already worked on this
Please select another issue
Closing the issue
