### ISSUE TITLE
Redesign complaints form

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#34]

**Comment by devYusuf** [comment]
I've redisigned it PR https://github.com/hngi/sentry-my-customer-frontend/pull/68

**Comment by sosualfred** [comment]
Go and comment here: I am working on this task assigngned to me by kadet. My slack username: @sosualfred

**Comment by kofimokome** [comment]
seriosly?
how can two of you work on same task.  let me get to Kadet

**Comment by sosualfred** [comment]
Hmm...I wonder

**Comment by kofimokome** [comment]
@devYusuf Kadet says @sosualfred  is the one to do the task.
Sorry I've no say since it's frontend. so you PR will be closed

**Comment by kofimokome** [comment]
I shall reopen it if sosualfred fails to deliver on time
