### ISSUE TITLE
Auth Guard for routes

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#36]
Create a custom auth guard to redirect a user not logged in to the admin page
And also, if the user is logged in and opens the login/register page, he will be redirected to the dashboard.

To summarize, this guard should prevent a user who is not logged in from accessing the dashboard

Use the the api_token cookie to do your authenticatoin

**Comment by kofimokome** [comment]
task assigned already

**Comment by Douglasokolaa** [comment]
Can I do it ?

**Comment by Jeremiahiro** [comment]
DM me on slack @jeremiahiro

**Comment by Jeremiahiro** [comment]
assigned to @Douglasokolaa 

slack: @doug
