### ISSUE TITLE
Create UI for customer

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#40]
This UI will have the following
- [x] View all customers
- [ ] View a specific customer
- [ ] Edit a customer
- [ ] Also a delete user button
- [x] the UI should be similar in design to the users list UI

**Comment by kay-ai** [comment]
I am currently working on this task

**Comment by kay-ai** [comment]
slack name @KC

**Comment by kofimokome** [comment]
who assigned it to you?

**Comment by kofimokome** [comment]
@karenEfereyan your work is left
