### ISSUE TITLE
Create UI for stores

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#42]
This UI will have the following

- [x] View all stores
- [x]  View a specific store
 - [x] Edit a store
- [x]  Also a delete user button
 - [x] the UI should be similar in design to the users list UI

**Comment by kadetXx** [comment]
I'm working on this task. 
Slack username: @kadet

**Comment by kofimokome** [comment]
approved

**Comment by kofimokome** [comment]
@SkyC0de

**Comment by SkyC0der** [comment]
I'm continuing the task from where Kadet stopped
Slack Name : @SkyCoder

**Comment by kofimokome** [comment]
approved
