### ISSUE TITLE
Link Store Page To The API

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#43]
You are required to integrate the following: 
- [ ] add store endpont
- [ ] Delete store endpoint
- [ ] Update store endpoint
- [ ] View store endpoint
- [ ] View all stores endpoint

**Comment by TokyoTG** [comment]
I can do this if the page is available

**Comment by kofimokome** [comment]
@TokyoTG  you have already a task na.
Let's try others first

**Comment by kofimokome** [comment]
@TokyoTG you can claim this if no one owns up
