### ISSUE TITLE
Add Logout route

### ISSUE THREAD

**Issue by kofimokome** [hngi/sentry-my-customer-frontend#77]
Currently, we are able to register and login, but not able to logout.
You are required to add the logout function

when a user logouts, all you need to do is to clear the  cookies created during registration / login especially the api_token

**Comment by sosualfred** [comment]
Why didn't you use the basic auth scaffolding for Laravel? It has all of this included.

**Comment by kofimokome** [comment]
it will not work @sosualfred , we need to create a another function to handle this

**Comment by sosualfred** [comment]
Can I work on it?

**Comment by kofimokome** [comment]
@sosualfred this is backend only.
I thought you are frontend dev

**Comment by sosualfred** [comment]
I can work it. I am full stack dev.

Started doing laravel 2 years ago.

**Comment by kofimokome** [comment]
Assinged to @doug
